# Application options
CONFIG_APP_FW_VERSION=10

CONFIG_APP_CONSEC_ADVERTISING_START_MS=9600
CONFIG_APP_ADVERTISING_TIMEOUT_MS=45000
CONFIG_APP_INITIAL_ADVERTISING_TIMEOUT_MS=120000
CONFIG_APP_ADVERTISE_ON_DISCONNECT=y

CONFIG_APP_VL53_DETECTION_INTERVAL_MS=240
CONFIG_APP_VL53_DISTANCE_THRESH_MM=910
CONFIG_APP_VL53_WATCHDOG_PERIOD_MS=300000

CONFIG_APP_SHT_ENABLE=y
CONFIG_APP_SHT_READ_INTERVAL_MS=900000

CONFIG_APP_SCHEDULE_MAX_SLEEP_MS=1800000

CONFIG_APP_STREAM_MAX_ERR=8
CONFIG_APP_ZMS_MAX_EVICTION_ATTEMPTS=8

CONFIG_APP_LOG_OVERWRITE_OLDEST=y

CONFIG_APP_BOARD_IS_PROD=y

CONFIG_APP_STREAM_WQ_STACK_SIZE=2048
CONFIG_APP_SENSOR_WQ_STACK_SIZE=2048

CONFIG_APP_CONSEC_DETECT_FILTER=n
# CONFIG_APP_CONSEC_DETECT_FILTER_COUNT=2

CONFIG_APP_WDT_TIMEOUT_MS=60000
CONFIG_APP_WDT_FEED_INTERVAL_MS=50000
CONFIG_APP_WDT_HEARTBEAT_INTERVAL_MS=45000


# System options
CONFIG_CLOCK_CONTROL_NRF_K32SRC_XTAL=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_20PPM=y
CONFIG_TICKLESS_KERNEL=y

CONFIG_WATCHDOG=y
CONFIG_TASK_WDT=y

CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_MAIN_STACK_SIZE=2048

CONFIG_PM_DEVICE=y 
CONFIG_PM_DEVICE_RUNTIME=y
CONFIG_PM_DEVICE_RUNTIME_USE_DEDICATED_WQ=y

CONFIG_RING_BUFFER_LARGE=y

CONFIG_ZMS=y
CONFIG_SETTINGS=y
CONFIG_SETTINGS_ZMS=y

CONFIG_ZMS_LOOKUP_CACHE=y
CONFIG_ZMS_LOOKUP_CACHE_SIZE=128

CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_MPU_ALLOW_FLASH_WRITE=y

CONFIG_DK_LIBRARY=n


# Bluetooth options
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="AZSensorSuite"
CONFIG_BT_DEVICE_APPEARANCE=1344
CONFIG_BT_MAX_CONN=1
CONFIG_BT_MAX_PAIRED=1

CONFIG_BT_PERIPHERAL_PREF_MIN_INT=250
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=250
CONFIG_BT_PERIPHERAL_PREF_LATENCY=0
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400

CONFIG_BT_CTLR_DATA_LENGTH_MAX=251
CONFIG_BT_BUF_ACL_RX_SIZE=251
CONFIG_BT_BUF_ACL_TX_SIZE=251
CONFIG_BT_L2CAP_TX_MTU=247
CONFIG_BT_CTLR_PHY_2M=y
CONFIG_BT_AUTO_PHY_UPDATE=y
CONFIG_BT_AUTO_DATA_LEN_UPDATE=y

CONFIG_BT_GATT_CLIENT=y
CONFIG_BT_GATT_AUTO_UPDATE_MTU=y

CONFIG_BT_EXT_ADV=y
CONFIG_BT_EXT_ADV_MAX_ADV_SET=1
CONFIG_BT_ATT_PREPARE_COUNT=2
CONFIG_BT_GATT_SERVICE_CHANGED=y

CONFIG_BT_SMP=y
CONFIG_BT_SMP_ALLOW_UNAUTH_OVERWRITE=y
CONFIG_BT_SETTINGS=y
CONFIG_BT_BONDABLE=y
CONFIG_BT_SMP_ENFORCE_MITM=n


# Peripheral options
CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_FPU=y

CONFIG_SENSOR=y
CONFIG_SHT3XD=y

CONFIG_SPI=n
CONFIG_ADC=n
CONFIG_PWM=n
CONFIG_CAN=n


# Firmware development options (disable in production)
CONFIG_USE_SEGGER_RTT=n
CONFIG_SERIAL=n

CONFIG_LOG=n
CONFIG_LOG_BACKEND_RTT=n
CONFIG_LOG_BACKEND_UART=n

CONFIG_PRINTK=n
CONFIG_BOOT_BANNER=n

CONFIG_UART_CONSOLE=n
CONFIG_RTT_CONSOLE=n


